packages:
  - "."

allowBuilds:
  unrs-resolver: true

patchedDependencies:
  expo-blur@57.0.3: patches/expo-blur@57.0.3.patch
  expo-modules-core@57.0.20: patches/expo-modules-core@57.0.20.patch
  expo-modules-jsi@57.1.1: patches/expo-modules-jsi@57.1.1.patch
